[build]
ignore = "if  [ ${COMMIT_REF} == ${CACHED_COMMIT_REF} ] ; then false ; else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- docs mkdocs.yml /packages/payment-proxy-client packages/nitro-rpc-client ; fi"
