#!/bin/bash

# exit immediately when any command fails
set -e

go build ./... 
golangci-lint run # this will fail if the code is formatted incorrectly, see ./.golangci.yml
go test ./...
go mod tidy # this may generate some changes...
go fmt ./...
git diff --exit-code # ...this will fail unless the working tree is clean