usedurablestore = true
durablestorefolder = "/app/data"

msgport = 3005
rpcport = 4005
guiport = 5005

# State Channel Public Address: 0x3E6b9c3e569e72932Cfc2A943E5497ed07FEfB9e
pk = ""

# Chain Public Address: 0x56032FA02b2592338b9A42B1865d5a5BEEaF2B75
chainpk = ""

naaddress = "0xe32d4B5C5a80660710f6a2aD3cB1c11664138F34"
vpaaddress = "0x4D1a804e1cE383D75032C52878553212992C98D7"
caaddress = "0x0C9D79725afc344A388045235CD0B23eA4f0E838"

# RPC provider docs: https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint
chainurl = "wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0"
chainstartblock = 907318
chainauthtoken = ""

bootpeers = ""/ip4/67.207.88.72/tcp/3005/p2p/16Uiu2HAmHQe7ej1swi9ghLwCi5jdSxLpGP3weBaE7j5ixBf5Hbzx""
