usedurablestore = true
durablestorefolder = "/app/data"

msgport = 3005
rpcport = 4005
guiport = 5005

# State Channel Public Address: 0x89825D58A7E2C198a06125be9CD0631317f9A07B
pk = ""

# Chain Public Address: 0x16e43DDc5FE417046Da7A0C469cCD4DE6b4764fA
chainpk = ""

naaddress = "0xe32d4B5C5a80660710f6a2aD3cB1c11664138F34"
vpaaddress = "0x4D1a804e1cE383D75032C52878553212992C98D7"
caaddress = "0x0C9D79725afc344A388045235CD0B23eA4f0E838"

# RPC provider docs: https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint
chainurl = "wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0"
chainstartblock = 908130
chainauthtoken = ""

bootpeers = ""

tlscertfilepath = "/etc/letsencrypt/live/iris-node.statechannels.org/fullchain.pem"
tlskeyfilepath = "/etc/letsencrypt/live/iris-node.statechannels.org/privkey.pem"
