name: mkcert

description: "Install mkcert and generate certificates"
runs:
  using: "composite"
  steps:
    - name: Install mkcert
      run: |
        curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
        chmod +x mkcert-v*-linux-amd64
        sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
        mkcert -install

    - name: Generate certificates
      run: |
        make -C tls create-cert
