name: Check Bindings and Lockfile

on:
  push:
    branches: [main]
  pull_request:
    paths:
      [
        "packages/nitro-protocol/contracts/**",
        "generate-adjudicator-bindings.sh",
        ".github/workflows/bindings-check.yml",
        "node/engine/chainservice/adjudicator/NitroAdjudicator.go",
        "node/engine/chainservice/consensusapp/ConsensusApp.go",
        "node/engine/chainservice/erc20/Token.go",
        "node/engine/chainservice/virtualpaymentapp/VirtualPaymentApp.go",
      ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install go-ethereum (includes abigen)
        run: go install github.com/ethereum/go-ethereum

      - name: make bin folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install solc
        run: |
          curl -o solc https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.17+commit.8df45f5f
          mv solc $GITHUB_WORKSPACE/bin
          sudo chmod +x $GITHUB_WORKSPACE/bin/solc

      - name: Regenerate contract bindings
        run: sh ./generate-adjudicator-bindings.sh

      - name: check git tree is clean
        # This will fail the job if any previous step (re)generated a file
        # that doesn't match what you checked in (or forgot to check in)
        run: git diff --exit-code
