name: Check Bindings and Lockfile

on:
  push:
    branches: [main]
    paths: "nitro-protocol/contracts/**"
  pull_request:
    paths: "nitro-protocol/contracts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          cd ./nitro-protocol
          npm install

      - name: make bin folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install solc
        run: |
          curl -o solc https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.7.4+commit.3f05b770 
          mv solc $GITHUB_WORKSPACE/bin
          sudo chmod +x $GITHUB_WORKSPACE/bin/solc

      - name: Install abigen (part of go-ethereum)
        run: |
          curl -o geth.tar.gz https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-amd64-1.10.8-26675454.tar.gz
          tar -xzf geth.tar.gz
          mv geth-alltools-linux-amd64-1.10.8-26675454/abigen $GITHUB_WORKSPACE/bin
          sudo chmod +x $GITHUB_WORKSPACE/bin/abigen

      - name: Regenerate contract bindings
        run: sh ./generate-adjudicator-bindings.sh

      - name: check git tree is clean
        # This will fail the job if any previous step (re)generated a file
        # that doesn't match what you checked in (or forgot to check in)
        run: git diff --exit-code
