name: Check Bindings and Lockfile

on:
  push:
    branches: [main]
  pull_request:
    paths: ["nitro-protocol/contracts/**", generate-adjudicator-bindings.sh]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - name: Install dependencies
        run: |
          cd ./nitro-protocol
          npm ci --legacy-peer-deps

      - name: make bin folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install solc
        run: |
          curl -o solc https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.17+commit.8df45f5f
          mv solc $GITHUB_WORKSPACE/bin
          sudo chmod +x $GITHUB_WORKSPACE/bin/solc

      - name: Install abigen (part of go-ethereum)
        run: |
          curl -o geth.tar.gz https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-amd64-1.12.2-bed84606.tar.gz
          tar -xzf geth.tar.gz
          mv geth-alltools-linux-amd64-1.12.2-bed84606/abigen $GITHUB_WORKSPACE/bin
          sudo chmod +x $GITHUB_WORKSPACE/bin/abigen

      - name: Regenerate contract bindings
        run: sh ./generate-adjudicator-bindings.sh

      - name: check git tree is clean
        # This will fail the job if any previous step (re)generated a file
        # that doesn't match what you checked in (or forgot to check in)
        run: git diff --exit-code
