name: Check Bindings and Lockfile

on:
  push:
    branches: [main]
  pull_request:
    paths:
      [
        'packages/nitro-protocol/contracts/**',
        'generate-adjudicator-bindings.sh',
        '.github/workflows/bindings-check.yml',
        'node/engine/chainservice/adjudicator/NitroAdjudicator.go',
        'node/engine/chainservice/consensusapp/ConsensusApp.go',
        'node/engine/chainservice/erc20/Token.go',
        'node/engine/chainservice/virtualpaymentapp/VirtualPaymentApp.go'
      ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'yarn'

      - name: Install go-ethereum (includes abigen)
        run: go install github.com/ethereum/go-ethereum

      - name: Install nitro-protocol dependencies
        run: |
          cd ./packages/nitro-protocol
          yarn

      - name: Regenerate contract bindings
        run: sh ./generate-adjudicator-bindings.sh

      - name: check git tree is clean
        # This will fail the job if any previous step (re)generated a file
        # that doesn't match what you checked in (or forgot to check in)
        run: git diff --exit-code
