name: Contracts

on:
  push:
    branches: [main]
  pull_request:
    paths: ["packages/nitro-protocol/**", ".github/workflows/contracts.yml"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/nitro-protocol
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          cache: "yarn"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      - name: Compile contracts
        run: yarn hardhat compile
      - name: Run gas benchmarks
        run: yarn benchmark:diff
      - name: Run contract tests
        run: yarn test:contracts
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./**/*.log
